version: '3'
services:
  web:
    build: .
    volumes:
      - .:/cookbook
    links:
      - db
    ports:
      - 80:3000
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
  db:
    image: postgres

